apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${kubernetes-serviceaccount-name}
subjects:
  - kind: ServiceAccount
    name: ${kubernetes-serviceaccount-name}
    namespace: ${namespace}
roleRef:
  kind: ClusterRole
  name: ${cluster-role}
  apiGroup: rbac.authorization.k8s.io
