redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

configs:
  cm:
    #use annotation for tracking but keep labels for compatibility with other tools
    application.resourceTrackingMethod: annotation+label
