initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.0
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  provider: aws
  backupStorageLocation:
    bucket: ${bucket}
  volumeSnapshotLocation:
    config:
      region: ${region}

credentials:
  useSecret: false
