---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: ${aws-provider-name}
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:${provider-aws-version}
  controllerConfigRef:
    name: ${aws-controller-config}
