# https://github.com/upbound/provider-aws/blob/main/docs/Configuration.md#create-a-provider
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: ${upbound-aws-provider-name}
spec:
  package: xpkg.upbound.io/upbound/provider-aws:${upbound-provider-aws-version}
  controllerConfigRef:
    name: ${upbound-aws-controller-config}
