# Create default rules for monitoring the cluster
# Disable rules for unreachable components
defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false

# Disable component scraping for the kube controller manager, etcd, and kube-scheduler
# These components are not reachable on EKS
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false

prometheus:
  prometheusSpec:
    # Prometheus StorageSpec for persistent data on AWS EBS
    # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
    storageSpec:
     volumeClaimTemplate:
       spec:
         storageClassName: gp2
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 20Gi
