{{- if .Values.rbacEnable }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    checkov.io/skip: CKV_K8S_21
  labels:
{{ include "kuberay-operator.labels" . | indent 4 }}
  name: {{ include "kuberay-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name  }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kuberay-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
