{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    checkov.io/skip: CKV_K8S_21
  name: {{ template "kuberay-operator.serviceAccountName" . }}
  labels:
{{ include "kuberay-operator.labels" . | indent 4 }}
{{- end -}}
