{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kuberay-operator.serviceAccountName" . }}
  labels:
{{ include "kuberay-operator.labels" . | indent 4 }}
{{- end -}}
