name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - mkdocs.yml
      - README.md
      - '.github/workflows/publish-docs.yaml'

  release:
    types:
      - published

env:
  PYTHON_VERSION: 3.11

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mike==1.1.2 \
            mkdocs-material==9.4.7 \
            mkdocs-include-markdown-plugin==6.0.3 \
            mkdocs-awesome-pages-plugin==2.9.2

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: mike deploy main
        if: contains(github.ref, 'refs/heads/main')
        run: |
          mike deploy --push main

      - name: mike deploy new version
        if: contains(github.ref, 'refs/tags/v') && !github.event.release.prerelease
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          mike deploy --rebase --push --update-aliases "${VERSION}" latest
